# Welcome to Jekyll!
title: Sushovan Majhi
email: sushovan.majhi08@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.smajhi.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sushovan4

# Build settings  
markdown: kramdown	
theme: minima		
plugins:		
  - jekyll-feed
  - jekyll-sitemap	
collections:
  research-projects:
    output: false
  coding-projects:
    output: false
  teaching:
    output: false 

defaults:
  - scope:
      path: ""
      type: "research-projects"
    values:
      layout: "default"
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
